# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-05-16 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('biz', models.CharField(max_length=30)),
                ('ip', models.CharField(max_length=30)),
                ('celery_id', models.CharField(max_length=100)),
                ('status', models.CharField(default='queue', max_length=30)),
                ('log', models.TextField(blank=True, null=True)),
                ('result', models.BooleanField(default=False)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
